govbr_data:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      extensions:
        - aws
        - httpfs
        - parquet
        - iceberg
      plugins: 
        - module: delta
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
